# Generated by Django 6.1 on 2026-09-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('SERVICE_MANAGER', 'Service Manager'), ('TEAM_MANAGER', 'Team Manager'), ('SENIOR_ENGINEER', 'Senior Engineer'), ('JUNIOR_ENGINEER', 'Junior Engineer'), ('INTERN', 'Intern'), ('VIEWER', 'Viewer'), ('TECHNICIAN', 'Technician')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_organization_user')],
            },
        ),
    ]
