# Generated by Django 6.1 on 2026-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_servicemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('SERVICE_MANAGER', 'Service Manager'), ('TEAM_MANAGER', 'Team Manager'), ('SENIOR_ENGINEER', 'Senior Engineer'), ('JUNIOR_ENGINEER', 'Junior Engineer'), ('INTERN', 'Intern'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
