# Generated by Django 6.1 on 2026-10-05 12:18

import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORGANIZATION_CREATED', 'Organization created'), ('ORGANIZATION_MEMBER_ADDED', 'Organization Member Added'), ('ORGANIZATION_MEMBER_REMOVED', 'Organization Member Removed'), ('ORGANIZATION_MEMBER_ROLE_CHANGED', 'Organization member role changed'), ('USER_CREATED', 'User Created'), ('USER_DEACTIVATED', 'User Deacticated'), ('SERVICE_CREATED', 'Service created'), ('SERVICE_DELETED', 'Service Deleted'), ('TEAM_CREATED', 'Team Created'), ('TEAM_DELETED', 'Team Deleted'), ('TEAM_MEMBER_ADDED', 'Team Member Added'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_STATUS_CHANGED', 'Incident Status Changed'), ('INCIDENT_SEVERITY_CHANGED', 'Incident Severity Changed'), ('INCIDENT_ASSIGNED', 'Incident Assigned'), ('INCIDENT_UNASSIGNED', 'Incident Unassigned'), ('INCIDENT_ASSIGNEE_CHANGED', 'Incident Assignee Changed'), ('INCIDENT_TEAM_CHANGED', 'Incident Team Changed')], max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.query.Prefetch, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
