# Generated by Django 6.1 on 2026-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
