# Generated by Django 6.1 on 2026-10-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_tags'),
        ('organizations', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='organizations.team'),
        ),
    ]
