# Generated by Django 6.1 on 2026-10-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('SEVERITY_CHANGED', 'Severity Changed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('COMMENTED', 'Commented'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('TEAM_CHANGED', 'Team Changed')], max_length=20),
        ),
    ]
