# Generated by Django 6.1 on 2026-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incidentevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentcomment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('SEVERITY_CHANGED', 'Severity Changed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('COMMENTED', 'Commented'), ('TEAM_CHANGED', 'Team Changed')], max_length=20),
        ),
    ]
